version: '3.6'

services:
  db:
    image: postgres:11.6
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    # Docker hack to wait until postgres is up
    command: >
      bash -c "while ! nc -w 1 -z db 5432;
               do sleep 0.1;
               done;
               ./manage.py migrate;
               ./manage.py collectstatic --noinput;
               exec /usr/local/bin/uwsgi --chdir=/code --ini=/code/uwsgi.ini"
    build: .
    image: mal
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
