# Generated by Django 3.0.4 on 2020-03-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_document_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_pinned",
            field=models.BooleanField(default=False),
        ),
    ]
